### ISSUE TITLE
怎么退出呢

### ISSUE THREAD

**Issue by zhaopengme** [DarkSand/fetchman#1]
我跑了一个 demo, 已经没有任何任务了?怎么退出了.很不错的一个框架

**Comment by da2vin** [comment]
@zhaopengme 强制退出 ctrl+c

**Comment by mobailabs** [comment]
@DarkSand 提供一个程序的入口吧!当爬虫跑完的时候,可以手动调用

**Comment by da2vin** [comment]
@zhaopengme 我是否可以这样理解，提供一个停止爬虫的方法供用户使用？那样直接调用exit()方法就可以了。

**Comment by mobailabs** [comment]
对,是的.
