### ISSUE TITLE
不能调用自己的方法

### ISSUE THREAD

**Issue by zhaopengme** [DarkSand/fetchman#2]
![image](https://user-images.githubusercontent.com/1415418/36779916-7aad0b42-1cac-11e8-9e1e-2b356ffc16bf.png)

我定义了filterHref方法,一直不能调用这个,为什么呢,还是我的写法有问题呢

**Comment by da2vin** [comment]
@zhaopengme process入口必须要有返回值，无论是用yield还是return，你最好使用yield返回a_list的pipeItem 在pipline里面处理a_list
