### ISSUE TITLE
ip代理池的方法

### ISSUE THREAD

**Issue by ethan-phu** [DarkSand/fetchman#3]
你好！我仔细查阅了您的源码！觉得您代码里的ip代理池的设计不是太人性化，一般ip代理我们都是使用不是稳定的ip proxy但是像您这样直接写死在txt文件中，也就是这个文件里的ip proxy是一种稳定的ip，而且也没有刷新机制。建议添加刷新机制，一旦用完了，就可以自动添加新的ip proxy。谢谢你的阅读。

**Comment by da2vin** [comment]
谢谢提醒，因为工作原因现在这个框架暂时没有维护了。这个框架只是作为一个实验性质的框架，并未实际用于生产，在生产中我这边采取的方式是另外有一个程序将代理ip放在redis中动态维护，而不是放在文本中。需要的时候从redis中获取即可。欢迎pr~
