### ISSUE TITLE
关于cookie的问题

### ISSUE THREAD

**Issue by ethan-phu** [DarkSand/fetchman#4]
您好！您在你的文档中提到，需要在下载器中加载loginer但是，我看到源码中，没有地方调用Login这个方法，也就是用户将login这个方法写好，并返回登陆的cookie，您的源码里也没用使用这个cookie。这算是一个bug吗？请仔细检查一下源码！

**Comment by da2vin** [comment]
您好~文档有提到项目中暂时没有这个功能，欢迎pr~后续有时间我也有可能对其完善~

**Comment by ethan-phu** [comment]
好的！了解了。我这边已经对您的项目内部源码进行了优化。
